anchor_version = "0.19.0"

[workspace]
members = ["programs/reward-pool"]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"

[programs.localnet]
reward_pool = "ddS8eKxapy89xg5NDkQWS97GDrDxCh2ChVF2nbRoa4D"

#[programs.devnet]
#reward_pool = "ddS8eKxapy89xg5NDkQWS97GDrDxCh2ChVF2nbRoa4D"

#[programs.testnet]
#reward_pool = "SRwd1XTVscKXu9nMU8f6MfEf9cAzGPmbMe69CFmHvAH"

#[programs.mainnet]
#reward_pool = "SRwd1XTVscKXu9nMU8f6MfEf9cAzGPmbMe69CFmHvAH"